const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS',
  SEARCH_DOCUMENTS_SUCCESS = 'SEARCH_DOCUMENTS_SUCCESS',
  SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS',
  LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS',
  SET_CURRENT_USER = 'SET_CURRENT_USER',
  LOAD_DOCUMENTS_SUCCESS = 'LOAD_DOCUMENTS_SUCCESS',
  CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS',
  VIEW_DOCUMENT_SUCCESS = 'VIEW_DOCUMENT_SUCCESS',
  LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS',
  UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS',
  LOAD_ROLES_SUCCESS = 'LOAD_ROLES_SUCCESS',
  FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export default {
  CREATE_USER_SUCCESS,
  LOGIN_USER_SUCCESS,
  SET_CURRENT_USER,
  LOAD_DOCUMENTS_SUCCESS,
  CREATE_DOCUMENT_SUCCESS,
  LOAD_USERS_SUCCESS,
  LOAD_ROLES_SUCCESS,
  UPDATE_DOCUMENT_SUCCESS,
  VIEW_DOCUMENT_SUCCESS,
  SEARCH_DOCUMENTS_SUCCESS,
  SEARCH_USERS_SUCCESS,
  FETCH_USERS_SUCCESS
};
