const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const SET_CURRENT_USER = 'SET_CURRENT_USER';
const LOAD_DOCUMENTS_SUCCESS = 'LOAD_DOCUMENTS_SUCCESS';
const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export default {
  CREATE_USER_SUCCESS,
  ADD_FLASH_MESSAGE,
  LOGIN_USER_SUCCESS,
  SET_CURRENT_USER,
  LOAD_DOCUMENTS_SUCCESS,
  CREATE_DOCUMENT
};
